options:
  UNICORN_WORKERS:
    type: int
    default: 3
    description: Number of unicorn workers to use.
  DISCOURSE_DEVELOPER_EMAILS:
    type: string
    description: | 
      Comma separated list of email addresses who should be an admin. eg:
      "foo@example.com,bar@example.com"
  DISCOURSE_SMTP_ADDRESS:
    type: string
    description: The hostname where emails should be delivered.
  DISCOURSE_SMTP_PORT:
    type: int
    description: The port for the email server.
  DISCOURSE_SMTP_USER_NAME:
    type: string
    description: Username for the email server.
  DISCOURSE_SMTP_PASSWORD:
    type: string
    description: Password for the email server.
  DISCOURSE_CDN_URL:
    type: string
    description: Content Delivery Network hostname to use.